#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
  path: /hello
  controller: App\Controller\HelloController::hello

#tom:
#  path: /tom
#  controller: App\Controller\HelloController::tom